name: 'SocketChat'
version: 0.0.1
description: 'Server -> Client WebSocket bridge for Bukkit.'

author: NoEff3x
authors: [jacklink01, Colbydude]
website: http://voidteam.net/minecraft/chat

main: net.voidteam.socketchat.SocketChat
database: false
depend: [Essentials, PExChat]

commands:
  socketchat:
    description: 'Command set used by SocketChat.'
    aliases: [sc, webchat]
    usage: Syntax error! Simply type /socketchat <kick-all|kick> [username]