name: 'SocketChat'
version: 0.0.1
description: 'Server -> Client WebSocket bridge for Bukkit.'

author: NoEff3x
authors: [jAcKlInK01, Colbydude]
website: http://voidteam.net/minecraft/chat

main: net.voidteam.socketchat.SocketChat
database: false
depend: [JSONAPI, Essentials]

commands:
  socketchat:
    description: 'Command set used by SocketChat.'
    aliases: [sc, webchat]
<<<<<<< HEAD
    usage: Syntax error! Simply type /&lt;socketchat&gt; <args>
=======
    usage: Syntax error! Simply type /socketchat <args>
>>>>>>> 36adbce... Add network-structure along with some more required libraries.
